### ISSUE TITLE
Inlining `fs.open` calls

### ISSUE THREAD

**Issue by CodeWithOz** [claviska/esbuild-plugin-inline-import#1]
In my nodejs app, I'm using a package that has calls to `fs.open` to access files included in the package. esbuild dosn't handle this out of the box. Is there a way to do it with this plugin? You can read more [here](https://github.com/evanw/esbuild/issues/1375)

Thanks.

**Comment by claviska** [comment]
I'm not sure what you're asking. This plugin also uses [`fs.readFile`](https://github.com/claviska/esbuild-plugin-inline-import/blob/master/index.js#L46) so if `fs` isn't supported this plugin won't work either.
