### ISSUE TITLE
esbuild in watch mode doesn't rebuild on changes to inline files

### ISSUE THREAD

**Issue by pjeby** [claviska/esbuild-plugin-inline-import#3]
Apparently, esbuild doesn't add watches for files in non-`file` namespaces, so inlined files aren't watched.  Adding `watchFiles: [args.path]` to the return value of the `build.onLoad()` callback seems to fix the issue, though.

**Comment by claviska** [comment]
Is this something the plugin could possibly do under the hood, or should we just document it so users know inlined files aren't watched without that line?

**Comment by pjeby** [comment]
What I meant was that I got it to work by patching the plugin, so that the [return statement here](https://github.com/claviska/esbuild-plugin-inline-import/blob/master/index.js#L52-L55) includes `watchFiles: [args.path]` in the returned object.  It's not something you can do from your esbuild configuration without replacing the entire plugin, basically. So the plugin definitely can do it under the hood, because that's the only way to do it as far as I can tell.

**Comment by claviska** [comment]
Thanks for clarifying. Is this something you'd like to PR or would you rather me handle it?

**Comment by pjeby** [comment]
Since it's just a one-line change, it seemed simpler for you to do it than to go through all the steps to fork and whatnot.  (I just hacked it directly in node\_modules during my testing.)

**Comment by SunsetTechuila** [comment]
hello, is this still relevant?

**Comment by pjeby** [comment]
I've filed a PR for this (#4).

**Comment by SunsetTechuila** [comment]
thank you

**Comment by claviska** [comment]
Published. Thanks for the PR!
